services:
  db:
    image: postgres:15.2
    container_name: poke-db
    environment:
      POSTGRES_USER: poke
      POSTGRES_PASSWORD: poke
      POSTGRES_DB: poke_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - poke-network

  api:
    build: .
    container_name: poke-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/poke_db
      SPRING_DATASOURCE_USERNAME: poke
      SPRING_DATASOURCE_PASSWORD: poke
    depends_on:
      - db
    networks:
      - poke-network

volumes:
  postgres_data:

networks:
  poke-network:
    driver: bridge